version: '3'

services:
  app:
    image: srigi/webauthn-nette/app
    build:
      context: .
      args:
        IS_PROD_BUILD: 0
    env_file:
      - .env
    volumes:
      - ./.data:/app/.data
      - ./.docker/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./config:/app/config
      - ./logs:/app/logs
      - ./src:/app/src
      - ./temp:/app/temp
      - ./www:/app/www

  webserver:
    image: srigi/webauthn-nette/webserver
    build:
      context: .
      dockerfile: Dockerfile.webserver
      args:
        CONFIG: 'nginx.dev-ssl.conf'
        STATIC_FILES_IMAGE: srigi/webauthn-nette/app
    env_file:
      - .env
    environment:
      BACKEND_SERVICE: app:9000
      FCGI_READ_TIMEOUT: 3600s
    ports:
      - 8000:8000
